repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
  - repo: https://github.com/python/black
    rev: 23.7.0
    hooks:
      - id: black